/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.cells.model;

import java.util.Objects;
import com.aspose.cloud.cells.model.MergedCells;
import com.aspose.cloud.cells.model.SaaSposeResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MergedCellsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-02T16:48:31.575+08:00")
public class MergedCellsResponse extends SaaSposeResponse {
  @SerializedName("MergedCells")
  private MergedCells mergedCells = null;

  public MergedCellsResponse mergedCells(MergedCells mergedCells) {
    this.mergedCells = mergedCells;
    return this;
  }

   /**
   * Get mergedCells
   * @return mergedCells
  **/
  @ApiModelProperty(value = "")
  public MergedCells getMergedCells() {
    return mergedCells;
  }

  public void setMergedCells(MergedCells mergedCells) {
    this.mergedCells = mergedCells;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergedCellsResponse mergedCellsResponse = (MergedCellsResponse) o;
    return Objects.equals(this.mergedCells, mergedCellsResponse.mergedCells) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mergedCells, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergedCellsResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    mergedCells: ").append(toIndentedString(mergedCells)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

