/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.cells.model;

import java.util.Objects;
import com.aspose.cloud.cells.model.Link;
import com.aspose.cloud.cells.model.LinkElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OleObjects
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-04T14:16:31.808+08:00")
public class OleObjects {
  @SerializedName("link")
  private Link link = null;

  @SerializedName("OleObjectList")
  private List<LinkElement> oleObjectList = null;

  public OleObjects link(Link link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @ApiModelProperty(value = "")
  public Link getLink() {
    return link;
  }

  public void setLink(Link link) {
    this.link = link;
  }

  public OleObjects oleObjectList(List<LinkElement> oleObjectList) {
    this.oleObjectList = oleObjectList;
    return this;
  }

  public OleObjects addOleObjectListItem(LinkElement oleObjectListItem) {
    if (this.oleObjectList == null) {
      this.oleObjectList = new ArrayList<LinkElement>();
    }
    this.oleObjectList.add(oleObjectListItem);
    return this;
  }

   /**
   * Get oleObjectList
   * @return oleObjectList
  **/
  @ApiModelProperty(value = "")
  public List<LinkElement> getOleObjectList() {
    return oleObjectList;
  }

  public void setOleObjectList(List<LinkElement> oleObjectList) {
    this.oleObjectList = oleObjectList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OleObjects oleObjects = (OleObjects) o;
    return Objects.equals(this.link, oleObjects.link) &&
        Objects.equals(this.oleObjectList, oleObjects.oleObjectList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, oleObjectList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OleObjects {\n");
    
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    oleObjectList: ").append(toIndentedString(oleObjectList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

